name: recsys3
channels:
  - defaults
dependencies:
  - notebook
  - pandas
  - jupyter
  - seaborn
  - numpy
  - scipy
  - pip
  - scikit-learn
  - matplotlib
  - python==3.10.18
  - tqdm
  - pyarrow
  - fastparquet
  - faiss-gpu